### ISSUE TITLE
Get jedis instance in non-jersey resource

### ISSUE THREAD

**Issue by sohussain** [benjamin-bader/droptools#11]
Is there anyway to get a `jedis` object from the pool in a non jersey resource, e.g. in a running eventbus listener?

**Comment by benjamin-bader** [comment]
You can definitely `@Inject` `JedisPool` objects if you are using HK2.  Right now, `Jedis` instances themselves are bound as `RequestScoped` in the HK2 machinery; while it's certainly possible to declare your bus-listener's dependency as per-request, it's probably not what you want.

If you are using Guice, you should investigate the HK2-bridge (https://hk2.java.net/guice-bridge/).  I haven't any experience with it personally.

Finally, you can get the pool directly during app start with `JedisBundle#getPool()`, once it is initialized, and give it to your bus listener by hand.
