### ISSUE TITLE
Problem selecting Oracle technologies

### ISSUE THREAD

**Issue by floupi** [benjamin-bader/droptools#12]
When configuring the JooqFactory from the dropwizard config, the enumeration values available for dialect are quite reduced from the ones of original jooq framework, for instance Oracle technologies cannot be selected.
btw great project !

**Comment by benjamin-bader** [comment]
Interesting!  Are you using the free version of jOOQ, or the paid version?  There are quite a few bits pertaining to proprietary databases like Oracle that are not included in the open-source edition, which is what I have available.

What things are you missing?  If it is as simple as enumeration values, then perhaps you can plug them in to the config file and it might just work.  If it's more than that, I'm not sure what the best approach is.  Having a specific use case would help with that.

**Comment by floupi** [comment]
I'm using the free version, you are certainly right I didn't realize that
this was a limitation of it. (cf. the *commercial
<http://www.jooq.org/javadoc/3.2.0/org/jooq/SQLDialect.html#commercial()>*
() from the API  :
http://www.jooq.org/javadoc/3.5.0/org/jooq/SQLDialect.html)
The test case is pretty straitforward, with this line in you config.yml for
the JooqFactory :
>
> dialect: ORACLE

Thanks

2015-04-23 0:02 GMT+02:00 Ben Bader <notifications@github.com>:

> Interesting! Are you using the free version of jOOQ, or the paid version?
> There are quite a few bits pertaining to proprietary databases like Oracle
> that are not included in the open-source edition, which is what I have
> available.
>
> What things are you missing? If it is as simple as enumeration values,
> then perhaps you can plug them in to the config file and it might just
> work. If it's more than that, I'm not sure what the best approach is.
> Having a specific use case would help with that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benjamin-bader/droptools/issues/12#issuecomment-95352229>
> .
>



-- 
Bruno WAGNER

**Comment by benjamin-bader** [comment]
Thanks for the followup.

You will definitely never be able to use `dialect: ORACLE` using the free version of jOOQ; this is a limitation of that library, not of this project.  In the free version, that enum value simply doesn't exist.  If you were using the commercial version, I don't see any reason why it wouldn't work.

If you have an Oracle database at your disposal, then likely the cost of a jOOQ license will be trivial in comparison, and well worth the expense :)

All that being said, I'm not sure there's anything to be done here, except possibly update the docs to spell out the distinction between free and commercial versions.  Please feel free to re-open if there's something that I'm missing on the droptools side.
