### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by tutfoo** [benjamin-bader/droptools#15]
Hi Ben,

Just wondering when you'll be able to do a release or upload a snapshot to Sonatype Nexus. We here at Lasso are eager to utilize the recent changes from a public domain.

Thanks!

**Comment by benjamin-bader** [comment]
Hi tutfoo

My attention has definitely drifted elsewhere recently, so I'm glad for the reminder!

I'll take a look in the next few days - let's keep this open until then.

**Comment by tutfoo** [comment]
Hi Ben! Just a friendly bump to let you know this is still alive :D

**Comment by benjamin-bader** [comment]
Part of the reason this took so long is that I've switched jobs, and I've had to recreate my peculiar Maven setup for making releases.

Anyhow, 0.8.1-1 is released, and should be generally available in Maven Central within the few hours.  Sorry for the lengthy wait.

**Comment by tutfoo** [comment]
This is great news, thanks Ben! And no worries, I know how much of a pain it can be working with old code. Future self > old self.

**Comment by benjamin-bader** [comment]
Let me know if you hit any problems.  The hard part is done, so follow-on fixes can happen quickly.  I'll close this issue now; please re-open if we need to make a bugfix release.
