### ISSUE TITLE
Jedis 2.8.0

### ISSUE THREAD

**Issue by sheldon-sminq** [benjamin-bader/droptools#16]
Can the package be updated to use Jedis 2.8.0

**Comment by benjamin-bader** [comment]
Thanks for being patient - I've been away from this repo for quite a while.

I'm not sure what (if anything) has changed in Jedis 2.8.0, but if the public API is still compatible you can supply your own copy in your Maven build (assuming you're using Maven):

```
  <dependency>
    <groupId>com.bendb.droptools</groupId>
    <artifactId>dropwizard-redis</artifactId>
    <version>0.8.1-1</version>
    <exclusions>
      <exclusion>
        <groupId>redis.clients</groupId>
        <artifactId>jedis</artifactId>
      </exclusion>
    </exclusions>
  </dependency>

  <dependency>
    <groupId>redis.clients</groupId>
    <artifactId>jedis</artifactId>
    <version>2.8.0</version>
  </dependency>
```

Again, no guarantees that this will work.  I'll do a proper update soon.
