### ISSUE TITLE
0.9.1-SNAPSHOT unavailable at maven central

### ISSUE THREAD

**Issue by jschaf** [benjamin-bader/droptools#20]
Hi,

Would you mind pushing the latest changes to maven?  

Thank you,
joe

**Comment by benjamin-bader** [comment]
I use Sonatype to get artifacts into Maven Central.  As a rule, snapshots don't get synced the the central repository, only final releases do.  0.9.1 isn't quite a final release yet, but in the meantime you can add the Sonatype Snapshots repo to your pom.xml file and use the snapshot that way.

**Comment by jschaf** [comment]
gotcha, that'll works.  Thanks.

**Comment by jschaf** [comment]
I feel like I'm missing something, but I don't see it on sonatype:  https://oss.sonatype.org/index.html#nexus-search;gav~com.bendb.dropwizard~dropwizard-jooq~~~~kw,versionexpand

**Comment by benjamin-bader** [comment]
Thanks for letting me know - looks like the CI build didn't deploy like it is supposed to.  I've pushed a snapshot build manually, and verified that it is available:

https://oss.sonatype.org/content/repositories/snapshots/com/bendb/dropwizard/dropwizard-redis/0.9.1-1-SNAPSHOT/

I should have a release ready soon.

**Comment by jschaf** [comment]
Much appreciated, thank you.

**Comment by esnellman** [comment]
Thanks for pushing!  Did try https://jitpack.io but unittest blow up bc no DB.  Was doing it locally.

**Comment by benjamin-bader** [comment]
You're welcome!

I'm not sure I understand what you're saying about Jitpack.  Were you trying to use it as an artifact repo?  I would certainly expect that to fail - the example project causes no small amount of grief when it comes to packaging release builds.

**Comment by esnellman** [comment]
Yep! https://jitpack.io/com/github/benjamin-bader/droptools/v0.8.1-1/build.log

**Comment by benjamin-bader** [comment]
Yep, as I expected.  Jitpack can't work for now.  Does the new build in Maven Central meet your needs?

**Comment by esnellman** [comment]
yes it does. Thanks!!  I was using a locally built fork before.
