### ISSUE TITLE
Why is default DSLContext RequestScoped?

### ISSUE THREAD

**Issue by mickeyreiss** [benjamin-bader/droptools#23]
I noticed that the default `DSLContext` that is bound in the `JooqBinder` is `RequestScoped`, while the instances that injected for `@JooqInject` are not.

Is there a reason for this difference? Would there be any adverse effects to removing the `.in(RequestScoped.calss)` for the default hk2 binding of `DSLContext`?

**Comment by benjamin-bader** [comment]
That's a very understandable question to ask - it's not at all apparent, on reading the code, that everything is in fact injected at request scope.  `@JooqInject` applies only to request parameters, and so is inherently request-scoped.

To your second question, I'm not 100% but I'd be extremely reluctant to share `DSLContext` objects between requests.  The API, though fluent, doesn't preclude some sort of mutable state internally, and who wants to debug a cross-request bug - I certainly don't.  These objects are cheap, and anyways the kind of state you want to share is encapsulated in the actually-global `Configuration` object.

**Comment by mickeyreiss** [comment]
Thanks for the excellent explanation. 

To give some background: I was trying to use Jooq inside of a `ContainerRequestFilter`. I ended up finding a workaround—injecting into a Jersey `Feature` with `@JooqInject`. This seemed to work, so I suppose `@JooqInject` does work for more than just request parameters.

**Comment by benjamin-bader** [comment]
Huh - interesting!  I hadn't thought of that use case.

To the best of my understanding, each `@JooqInject` gives you a new `DSLContext` - if you inject your filter on each request, you'll have effectively a request-scoped object.  If not, then I suppose you wind up with a global object!  If it works, then who am I to argue against it.
