### ISSUE TITLE
Best way to get a DSLContext into a dropwizard task?

### ISSUE THREAD

**Issue by jensenbox** [benjamin-bader/droptools#26]
I am hunting for the ideal way to get a database handle into a task - striking out.

Any suggestions?

**Comment by benjamin-bader** [comment]
For needs like this I usually reach for dependency injection, e.g. Guice.  Dropwizard ships with HK2, a similar DI framework, which unfortunately is super cumbersome.  You could use it, or use Guice with the HK2 bridge library (whose name I've forgotten).

More simply, in your App class you could hold on to your `JooqBundle` and use it to obtain a jOOQ `Configuration`, which you can give to your task.  It might look something like the following:

```java
// in App.java

private JooqBundle<MyConfig> jooqBundle;

public void initialize(Bootstrap<MyConfig> bootstrap) {
  jooqBundle = new JooqBundle<MyConfig>() { /* code */ };
  bootstrap.addBundle(jooqBundle);

  // the rest of your initialization
}

public void run(MyConfig config, Environment environment) {
  Configuration jooqConfiguration = jooqBundle.getConfiguration();
  MyTask task = new MyTask(jooqConfiguration);

  environment.admin().addTask(task);
}
```

```java
// in MyTask.java
private Configuration jooqConfig;

public MyTask(Configuration jooqConfig) {
  this.jooqConfig = jooqConfig;
}

 @Override
public void execute(ImmutableMultimap<String, String> parameters, PrintWriter output) throws Exception {
  DSL.using(jooqConfig)
      .select(TABLE_NAME)
      .blah()
      .blah()
      .etc();
}
```

**Comment by jensenbox** [comment]
That worked beautifully!

I have been struggling to find out how exactly Tasks are different from Resources - like the core difference. I was super close to making my task just a void resource. I would get DSLContext for free then. Any insight as to what the motivation is?

Thanks again!

**Comment by benjamin-bader** [comment]
Well, you notice that you register a task with `environment.admin()`, which is a huge indication that tasks are for administrative things (i.e. things done by you for the operation of the service).  They're not intended to be REST-ful endpoints, or user-facing features.

Glad that helped - I haven't done Dropwizard in a while, so was not so confident that I had the sample right.
