### ISSUE TITLE
Cut a new release to support Dropwizard 0.9.1+

### ISSUE THREAD

**Issue by fredsadaghiani** [benjamin-bader/droptools#29]
Please deploy a new version to maven central that incorporates changes after a534f4e. In particular, this library cannot be used with Dropwizard 0.9.1+ since there is a conflict with Hibernate 5.2.x that was resolved with ed76d0f5f15c508b5c1ecef74a7e78ab61e63136.

Thanks!

**Comment by benjamin-bader** [comment]
Thank you for reminding me; I'll cut a release today or tomorrow.

**Comment by benjamin-bader** [comment]
I've just pushed release `0.9.3-0` to Maven Central; it should be available for download within 15 minutes.

I'm not a heavy Dropwizard user these days, so while I tested the usual things I may have missed some bugs.  Please do let me know if you hit any.  Thanks!
