### ISSUE TITLE
Not able to include this bundle using gradle

### ISSUE THREAD

**Issue by ganeshcse2991** [benjamin-bader/droptools#31]
I have included the following dependency on gradle dependencies but Its not resolving the package.
Unable to import jedis and bedb not found.

compile group: 'com.bendb.dropwizard', name: 'dropwizard-redis', version: '1.0.0-0'

**Comment by benjamin-bader** [comment]
It's available in Maven Central, and presumably in jCenter as well.  Try this:
`compile 'com.bendb.dropwizard:dropwizard-redis:1.0.0-0'`

I took that directly from Maven Central's site: http://search.maven.org/#artifactdetails%7Ccom.bendb.dropwizard%7Cdropwizard-redis%7C1.0.0-0%7Cjar

Also, make sure you have either `mavenCentral()` or `jcenter()` in your dependency repositories section.

**Comment by benjamin-bader** [comment]
Are you still having trouble, or is this issue resolved?
