### ISSUE TITLE
Can't customize Redis timeout

### ISSUE THREAD

**Issue by vasukisesh** [benjamin-bader/droptools#33]
Why is the Redis timeout not configurable? The default timeout of 2000ms may not always work.

**Comment by benjamin-bader** [comment]
I don't know why, but it hadn't occurred to me to add that configuration.  Sounds like a great idea - happy to take a pull request!

**Comment by vasukisesh** [comment]
Happy to submit one if you give me permissions to do push a branch.

**Comment by benjamin-bader** [comment]
Thanks for your kind offer!

The usual workflow on Github (and the one that I follow) is:
1. Fork the repo (using the "Fork" button on the top-right corner of the screen)
2. Make the changes in your local copy
3. Push the changes to your fork, (i.e. https://github.com/vasukisesh/droptools)
4. Open a pull request.

**Comment by vasukisesh** [comment]
Done, thanks!

**Comment by benjamin-bader** [comment]
Thanks, I appreciate the effort!  Your change will be available shortly in `1.0.0-2-SNAPSHOT`, and also whenever `1.0.0-2` goes out.  No timeline for the latter, but I'm thinking a week or two at the outside as this is a pretty quiet project.

**Comment by vasukisesh** [comment]
Great, thanks for the quick turnaround!

**Comment by benjamin-bader** [comment]
FYI, I just pushed version 1.0.0-2 (including your PR) to Maven Central.  search.maven.org should have it within 10-20 minutes.

**Comment by vasukisesh** [comment]
Great, thanks for the heads-up!
