### ISSUE TITLE
Custom Authenticator with AuthFilter + Jooq?

### ISSUE THREAD

**Issue by Gaudon** [benjamin-bader/droptools#37]
Is it possible to use the @Context annotation for database access via jooq when writing DropWizard custom authentication Filters?

I don't seem to be able to @Override the authenticate() methods while injecting the @Context annotation.

**Comment by Gaudon** [comment]
DropWizard projects generally contain a resources package (where @Context DSLContext database works fine) among several other packages. One of these being the suggested auth package where users can write their own custom authentication through means of an AuthenticationFilter. 

DashboardAuthenticator.java
```
@Override
@UnitOfWork
public Optional<DashboardUser> authenticate(DashboardCredentials credentials) throws AuthenticationException {
        SessionDTO sessionDTO = sessionDAO.findSession(credentials.getToken());
```

DashboardAuthFilter.java
```
@PreMatching
@Provider
@Priority(Priorities.AUTHENTICATION)
public class DashboardAuthFilter<P extends Principal> extends AuthFilter<DashboardCredentials, P> {

    private DashboardAuthenticator authenticator;

    public DashboardAuthFilter(DashboardAuthenticator authenticator) {
        this.authenticator = authenticator;
    }

    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {

        DashboardCredentials credentials = getCredentials(requestContext);

        final SecurityContext securityContext = requestContext.getSecurityContext();
        final boolean secure = securityContext != null && securityContext.isSecure();

        try {
            final Optional<DashboardUser> authUserResult = authenticator.authenticate(credentials);
            if(!authUserResult.isPresent()) {
                throw new WebApplicationException(Response.Status.UNAUTHORIZED);
            } else {
                requestContext.setSecurityContext(new SecurityContext() {
                    @Override
                    public Principal getUserPrincipal() {
                        return authUserResult.get();
                    }

                    @Override
                    public boolean isUserInRole(String s) {
                        return false;
                    }

                    @Override
                    public boolean isSecure() {
                        return secure;
                    }

                    @Override
                    public String getAuthenticationScheme() {
                        return "Dashboard";
                    }
                });
            }
        } catch (AuthenticationException e) {
            throw new WebApplicationException(Response.Status.UNAUTHORIZED);
        }
    }

    private DashboardCredentials getCredentials(ContainerRequestContext requestContext) {
        DashboardCredentials credentials = new DashboardCredentials();
        credentials.setToken(requestContext.getHeaderString("Authorization"));
        return credentials;
    }
}
```

The AuthFilter invokes the Authenticator in this case, whereby the Authenticator uses DropWizard DAO's to access the database to determine if a user is authenticated with the system (ie: by checking a token sent as a header for example). 

Is it possible to use Jooq here via your drop-tools helper and eliminate the need for the registered DAO objects with Jersey altogether?

**Comment by benjamin-bader** [comment]
`@Context` injection is not an option here, but HK2 injection should work.

It has been several years since I used Dropwizard regularly, so my knowledge is pretty stale; this is the first I've seen of `AuthFilter`, for example.  I recall that HK2 is pretty verbose to set up; for something like this, I'd probably just manually hand off an `org.jooq.Configuration` to the authenticator.

**Comment by Gaudon** [comment]
I'll take a look at the manual hand off and see if that's an avenue that might work. Thanks.
