### ISSUE TITLE
Previously deprecated guava HostAndPort.getHostString() now removed in DW-1.2.0's guava dependency

### ISSUE THREAD

**Issue by tvaughan77** [benjamin-bader/droptools#41]
Dropwizard 1.2.0 has upgraded to guava 23.1 (specifically `com.google.guava:guava:23.1-jre`) which has officially removed the `getHostString()` method on the `HostAndPort` object in the `com.google.common.net` package.

Deprecation notes: https://google.github.io/guava/releases/20.0/api/docs/deprecated-list.html

I think the "fix" to make your awesome JedisFactory work in a dropwizard 1.2.0 environment is as easy as replacing the call on line 108 from `endpoint.getHostString();` to `endpoint.getHost()`

I'll submit a PR shortly for that and it'd be _awesome_ if you could release a new dropwizard-redis for dropwizard 1.2.0 compatibility.

**Comment by benjamin-bader** [comment]
Sounds good to me!

**Comment by agoffer** [comment]
Hi @benjamin-bader 
I've seen the fix has been merged. Do you have plan to release a new version? 
Nice add-on to Dropwizard, would love to continue to use it.

**Comment by benjamin-bader** [comment]
Hi, sorry for the delay.  I've just pushed version `1.2.0-0` to Maven, which includes this fix.  It should be visible within the next 5-15 minutes.

Thanks again @tvaughan77 for the PR!
