### ISSUE TITLE
Release 1.3.5 has no published artifact (sonatype/maven)

### ISSUE THREAD

**Issue by daveooooooooo** [benjamin-bader/droptools#48]
The release on github occurred 25 days ago, but it hasn't been published yet for consumption by maven. https://oss.sonatype.org/#nexus-search;quick~dropwizard-redis

Is there a plan to publish the artifact there?

**Comment by benjamin-bader** [comment]
The plan is for Sonatype to fix their server; I've tried (and failed) numerous times to push a release.  Something is broken on their end.

**Comment by benjamin-bader** [comment]
JFYI, Still no luck pushing the release to Sonatype.  Having worked with their admin, we're both scratching our heads, and I've more or less exhausted my patience for the time being.

**Comment by benjamin-bader** [comment]
Hi, I finally got around to switching this project's build system to Gradle, which unblocked release pushes.

Version 1.3.5-1 should be available on Maven Central within the next 15 minutes or so.

**Comment by lukroth** [comment]
Hi,
I can not find a release on maven central for v1.3.5-1
https://mvnrepository.com/artifact/com.bendb.dropwizard/dropwizard-jooq
Is there a plan to publish the artifact there?
Thanks for your answer!

**Comment by benjamin-bader** [comment]
Whoops, I accidentally repackaged the project when I converted it to Gradle.  The artifacts are published as `com.bendb.droptools`, not `com.bendb.dropwizard`: https://mvnrepository.com/artifact/com.bendb.droptools/dropwizard-jooq

I suppose I should fix that.

**Comment by lukroth** [comment]
Hi,
Thanks for your fast Answer!
Great, this solves the issue :)
Cheers,
Lukas

**Comment by benjamin-bader** [comment]
I've just published 1.3.5-1 again, with the correct package.  You can revert back to `com.bendb.dropwizard` now - well, within the next 15 minutes or so :)

Thanks again for bringing the problem to my attention.

**Comment by lukroth** [comment]
Hi,
great, thanks!
Cheers,
Lukas
