### ISSUE TITLE
Inject @Context Jedis instance in unit test

### ISSUE THREAD

**Issue by gukkes** [benjamin-bader/droptools#51]
I'm trying to unit test a Resource that expects a Jedis instance (via @Context), via GrizzlyTestContainer, but I fail to succeed.

```
    @GET
    @Path("/foo")
    @ManagedAsync
    public void checkFoo(@Suspended AsyncResponse response, @Context final Jedis jedis) {
       ...
    }


@ClassRule
    public static final ResourceTestRule resources = ResourceTestRule.builder()
            .addResource(new MyResource())
            .setTestContainerFactory(new GrizzlyWebTestContainerFactory())
            .addProvider(...)
            .build();
```

How can I inject e.g. a mock Jedis instance? Should it go via addProvider()?

**Comment by benjamin-bader** [comment]
Apologies - I haven't used Dropwizard in nearly five years, and am thoroughly unfamiliar with `GrizzlyTestContainer`.  I have no advice to offer, except that if `addProvider()` will unblock you, go for it.

You will most likely have better luck finding e.g. a Grizzly (?) developer mailing list (or Jersey, or even the Dropwizard google group itself) and asking there about context injection in tests.
