### ISSUE TITLE
JedisPool hangs forever when a connection is not available

### ISSUE THREAD

**Issue by vasukisesh** [benjamin-bader/droptools#52]
JedisPool uses an Apache Commons Pool implementation which by default has a maxWaitMillis set to -1 (wait indefinitely). This causes the getPool() connection to hang indefinitely if all the available connections are in use. This is less than ideal from a consumer-point-of-view.

I suggest that we can set the poolConfig maxWaitMillis to match the connection timeout config used for the pool itself. Happy to submit a PR if needed.

**Comment by benjamin-bader** [comment]
Thank you, that's a great suggestion - please feel free to send a PR!

**Comment by vasukisesh** [comment]
Pull request #53 submitted.

**Comment by vasukisesh** [comment]
PR accepted, so I'm closing the issue.
