### ISSUE TITLE
Using a different Connection Pool

### ISSUE THREAD

**Issue by esnellman** [benjamin-bader/droptools#6]
I am unsure how the connections are being released by:
https://github.com/dropwizard/dropwizard/blob/master/dropwizard-db/src/main/java/io/dropwizard/db/ManagedPooledDataSource.java

I am considering https://github.com/brettwooldridge/HikariCP
sample:
https://gist.github.com/esnellman/2eb3df086baa8769ba60

Naturally I was thinking of modifying Factory<DSLContext> where the dispose(instance) would release a connection.  The jersey docs are unclear, do you know if dispose is always called even in the event of an exception?  Like a try with resource block?

**Comment by benjamin-bader** [comment]
As a `Managed` object, properly-registered `ManagedPoolDataSource` objects are properly closed down as part of the DW service lifecycle.  If the thing crashes, no such cleanup is guaranteed.

Individual connections are released back to the pool by their consumers.  A Hibernate session started by a `@UnitOfWork` annotation, for example, or a jOOQ `DSLContext` when it is finished executing.  With these libraries (but not in the general case!), you can rely on connections being returned to the pool without special effort.

As far as replacing the Tomcat connection pool with HikariCP, of course anything is possible - but I wouldn't recommend it.  Most SQL libraries for DW (including this one) explicitly depend on `dropwizard-db`, and though you certainly **could** do this you'd lose the use of the existing ecosystem.  Why do you wish to make the switch?

**Comment by esnellman** [comment]
Thank you for the fast reply!  Will be following your advice.
