### ISSUE TITLE
Dropwizard 3.0 and 4.0

### ISSUE THREAD

**Issue by daberkow** [benjamin-bader/droptools#63]
Hello!

I was wondering if you plan to update this library to work with the breaking changes in Dropwizard 3 and 4, a `PooledDataSourceFactory` is now needed over a `DataSourceFactory` in the new bundle.

Dan

**Comment by daberkow** [comment]
I got it working with a lot of updates! The main issue this library may now face is there are 2 branches of Dropwizard, and 2 versions of jOOQ (3.17 with Java 11+ support, and 3.18 with Java 17+ support), and picking which to support.

**Comment by vasukisesh** [comment]
@benjamin-bader @daberkow When can we expect a released version of this library with support for Dropwizard 3.x? I see this PR was merged over 3 months ago. Thanks!

**Comment by daberkow** [comment]
I actually ran into giant issues with Dropwizard 4.0 trying to get oauth working. I was trying to use Dropwizard 4 with Pac4J, at the time this had a dependency on `jax-rs-pac4j` which still used the `javax` namespace instead of Jakarta and was breaking the whole build.
I ended up pivoting away from using Dropwizard for that project for this reason. @benjamin-bader also spoke about using Dropwizard less in #64

**Comment by vasukisesh** [comment]
@daberkow Thanks for that information, but we're just looking for Dropwizard 3.x integration at this point. Since that has already been merged, I was hoping there would be a released version we could pull. Any chance of creating a release?

**Comment by benjamin-bader** [comment]
It's going to take some work; @daberkow's mega-commit upgraded our Gradle version which in turn broke our script to publish releases.  (It was known at the time, made necessary by Gradle's API evolution, and I just haven't gotten to fixing it yet).

**Comment by vasukisesh** [comment]
@benjamin-bader Ah I see. That's unfortunate. We only use maven, but I suppose that doesn't help for the release process. Will you be proceeding with a release, or should we pursue other avenues?

**Comment by benjamin-bader** [comment]
As I'm able.  This is a volunteer project I no longer personally use, so I'll get to it when I can.  If you're relying on this in production then once I figure that out, I'm happy to make you a maintainer going forward.

**Comment by daberkow** [comment]
If it helps at all, I have a repo that publishes to Maven Central with newer gradle! [https://github.com/daberkow/PodcastFeedHandler/blob/main/build.gradle](https://github.com/daberkow/PodcastFeedHandler/blob/main/build.gradle)

**Comment by benjamin-bader** [comment]
I typically use https://github.com/vanniktech/gradle-maven-publish-plugin for this and intend to do so here.

**Comment by benjamin-bader** [comment]
Well that was easier than I remembered.  Version 3.0.0-0 should hit the central repo in 15-30 minutes.

**Comment by vasukisesh** [comment]
Oh great, thank you for the quick turnaround!

**Comment by benjamin-bader** [comment]
I'm serious about the maintainer role though - it's yours.  I don't want to sit between you and production :)
